# Generated by Django 5.0.7 on 2024-07-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150)),
                ('conversation_name', models.CharField(max_length=150)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('anonymous', models.BooleanField()),
                ('team', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownder', models.CharField(max_length=150)),
                ('date_created', models.DateField()),
                ('conversation_id', models.ForeignKey(on_delete=models.SET(None), to='chatbotAPI.conversation')),
            ],
        ),
    ]
