# Generated by Django 5.0.7 on 2024-07-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotAPI', '0003_delete_user_remove_message_conversation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
    ]
