# Generated by Django 5.0.7 on 2024-07-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotAPI', '0004_remove_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chatbotAPI.message'),
        ),
    ]
