# Generated by Django 5.0.7 on 2024-07-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotAPI', '0005_conversation_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
